//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DScheduler.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJobMonitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TJobMonitor()
        {
            this.TJobActions = new HashSet<TJobAction>();
        }
    
        public int JobID { get; set; }
        public int SessionID { get; set; }
        public int UprocID { get; set; }
        public int EnvironmentID { get; set; }
        public int NodeID { get; set; }
        public Nullable<System.DateTime> ScheduleDateTime { get; set; }
        public Nullable<System.DateTime> StartedDateTime { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public string UProcStatus { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual TEnvironment TEnvironment { get; set; }
        public virtual TSession TSession { get; set; }
        public virtual TUproc TUproc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TJobAction> TJobActions { get; set; }
        public virtual TNode TNode { get; set; }
    }
}
