//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DScheduler.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOutageDetail
    {
        public int OutageDetailID { get; set; }
        public int OutageID { get; set; }
        public string OutageName { get; set; }
        public Nullable<System.DateTime> OutageDate { get; set; }
        public Nullable<System.DateTime> OutageStartTime { get; set; }
        public Nullable<System.DateTime> OutageEndTime { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual TOutage TOutage { get; set; }
    }
}
