//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSchedule.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TReport
    {
        public int ReportID { get; set; }
        public int TemplateID { get; set; }
        public string TemplateName { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual TTemplate TTemplate { get; set; }
    }
}
