//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DScheduler.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJobRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TJobRule()
        {
            this.TOutages = new HashSet<TOutage>();
            this.TRecurrencePatterns = new HashSet<TRecurrencePattern>();
        }
    
        public int JobRuleID { get; set; }
        public int ActivityTypeID { get; set; }
        public Nullable<decimal> SessionID { get; set; }
        public Nullable<decimal> UprocID { get; set; }
        public int OutageID { get; set; }
        public string SessionUprocName { get; set; }
        public Nullable<System.TimeSpan> JobStartTime { get; set; }
        public Nullable<bool> IsRecurrencePresent { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual TRef TRef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOutage> TOutages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRecurrencePattern> TRecurrencePatterns { get; set; }
    }
}
