//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DScheduler.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRecurrencePattern
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRecurrencePattern()
        {
            this.TRecurrencePatternDetails = new HashSet<TRecurrencePatternDetail>();
        }
    
        public int RecurrencePatternID { get; set; }
        public Nullable<int> RecPattTypeID { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public Nullable<int> NoOfMonths { get; set; }
        public Nullable<int> NoOfYears { get; set; }
        public string WeekName { get; set; }
        public string WeekDayName { get; set; }
        public string MonthName { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActiveRecurrence { get; set; }
        public int JobRuleID { get; set; }
    
        public virtual TJobRule TJobRule { get; set; }
        public virtual TRef TRef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRecurrencePatternDetail> TRecurrencePatternDetails { get; set; }
    }
}
