//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DScheduler.BusinessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRecurrencePatternDetail
    {
        public int RecurrrencePatternDetailsId { get; set; }
        public int RecurrencePatternId { get; set; }
        public string DayOfWeek { get; set; }
        public Nullable<int> DayOfMonth { get; set; }
        public Nullable<System.DateTime> DayOfYear { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual TRecurrencePattern TRecurrencePattern { get; set; }
    }
}
