//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJobAction
    {
        public int JobActionID { get; set; }
        public int JobID { get; set; }
        public int JobActionTypeID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual TRef TRef { get; set; }
        public virtual TJobMonitor TJobMonitor { get; set; }
    }
}
