//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDependency
    {
        public int DependentID { get; set; }
        public int SessionID { get; set; }
        public Nullable<int> UprocID { get; set; }
        public int SequenceNumber { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual TSession TSession { get; set; }
        public virtual TUproc TUproc { get; set; }
    }
}
